### ISSUE TITLE
Unpeg patch level dependency on big-integer

### ISSUE THREAD

**Issue by lpd-au** [ip-num/ip-num#26]
This repo unnecessarily depends on `big-integer@1.6.28`.  Version `1.6.37` leverages the new [native implementation of `BigInt`](https://developers.google.com/web/updates/2018/05/bigint) where available while maintaining backwards compatibility with the original api. Please consider changing your dependency to `^1.6.37` or releasing your own `2.0.0` that directly uses native `BigInt`.

**Comment by dadepo** [comment]
Thanks for bring this to my attention. This would be taken care of in #27 and would be part of the v1.3.x release.
