### ISSUE TITLE
Native BigInt

### ISSUE THREAD

**Issue by zdm** [ip-num/ip-num#59]
Hi.
Why not just use native `BigInt` class instead of `big-integer` package?
It is stable and appareared since node v10.

**Comment by dadepo** [comment]
`ip-num` has been in existence before `BigInt` was stabilised. Then, `big-integer` package was the available option, so that explains why it is in use.

That been said, I do have it in mind to drop it and move to `BigInt`. I'll keep this open and close it when I get around to doing that.

**Comment by znerol** [comment]
From the project page of [peterolson/BigInteger.js](https://github.com/peterolson/BigInteger.js/):

> This library now works as a polyfill: if the environment supports the native BigInt, this library acts as a thin wrapper over the native implementation.

Thus, I guess there is not so much immediate benefit from moving away from `big-integer`.

**Comment by kamilmielnik** [comment]
> Thus, I guess there is not so much immediate benefit from moving away from `big-integer`.

There is!
Currently one cannot pass `bigint` value to `IPv4.fromBigInteger` or `IPv6.fromBigInteger` - therefore it's necessary to wrap it with `big-integer` (extra code).

```ts
// error TS2345: Argument of type 'bigint' is not asignable to parameter of type 'BigInteger'.
IPv4.fromBigInteger(1n);
```

**Comment by dadepo** [comment]
@kamilmielnik FYI: A version `1.4.0-1` that drops big-integer and relies on native BigInt is available now. [See](https://www.npmjs.com/package/ip-num/v/1.4.0-1)
