### ISSUE TITLE
RangedSet.isCidrAble() incorrect results

### ISSUE THREAD

**Issue by zdm** [ip-num/ip-num#68]
```
import ipNum from "ip-num";

const range = ipNum.RangedSet.fromRangeString( "1.2.3.4-1.2.3.4" );

console.log( range.isCidrAble() ); // false
```
Why it is `false`? This range can be presented as `1.2.3.4/32`;

**Comment by dadepo** [comment]
That's a bug! Will be fixed in the next release. I'll update this ticket once that is done. Thanks for reporting!
