### ISSUE TITLE
Collapsing already collapsed IPv6 returns invalid IPv6 addr

### ISSUE THREAD

**Issue by ahayden-lg** [ip-num/ip-num#74]
Collapsing an already collapsed IPv6 address returns an invalid IPv6 address. This is important to collapse an IPv6 address, when it is not known if the address is already collapsed.

Example (v. 1.3.2):
```
var ipNum = require("ip-num")
ipNum.collapseIPv6Number("2123:470:1:b95::7316");
--> "2123:470:1:b95:0:7316"
```

**Comment by dadepo** [comment]
Thanks for reporting. Will be fixed soon. Will update this ticket when fix is released

**Comment by dadepo** [comment]
FYI: Version `1.3.3-1` is now available on `npm`, and contains the the fix for this. Still intend to add more features/improvement to the next release. So if everything goes smooth and barring no other bugs, v1.3.3 should be release in the next couple of weeks.

**Comment by dadepo** [comment]
Version `1.3.3` is now published
