### ISSUE TITLE
Multiple "::" not considered invalid

### ISSUE THREAD

**Issue by ahayden-lg** [ip-num/ip-num#75]
I noticed that invalid IPv6 values with 2 sets of "::" are not marked as in valid and are converted. But per the IPv6 specs only one "::" is allowed, because you can't tell how many 0s "::" should be expanded to if there are 2 "::"s.  For example, I would have expected each of the following to not be considered valid:
```
console.log(ipNum.expandIPv6Number("::123::"));
console.log(ipNum.collapseIPv6Number("12::123::"));
console.log(ipNum.Validator.isValidIPv6String("::123::234")[0]);

"0000:0000:0000:0000:0000:0000:0000:0123"
"12:0:123::"
true
```
Hopefully this is helpful.

**Comment by dadepo** [comment]
This is indeed helpful. Thanks for reporting. Will update once a fix is released.

**Comment by dadepo** [comment]
FYI: Version `1.3.3-1` is now available on `npm`, and contains the the fix for this. Still intend to add more features/improvement to the next release. So if everything goes smooth and barring no other bugs, v1.3.3 should be release in the next couple of weeks

**Comment by dadepo** [comment]
Version `1.3.3` is now published
