### ISSUE TITLE
v1.3.3-0 RangedSet.toIPv4CidrRange error

### ISSUE THREAD

**Issue by zdm** [ip-num/ip-num#76]
Range: `8.17.205.0-8.17.206.255`
`range.isCidrAble()` - `true`
`range.toIPv4CidrRange()` - `Error: Range cannot be converted to CIDR`

**Comment by dadepo** [comment]
Thanks for reporting this. Will update once a fix is available!

**Comment by dadepo** [comment]
FYI: Version `1.3.3-1` is now available on `npm`, and contains the the fix for this. Still intend to add more features/improvement to the next release. So if everything goes smooth and barring no other bugs, v1.3.3 should be release in the next couple of weeks

**Comment by dadepo** [comment]
FYI: Version `1.3.3-1` is now available on `npm`, and contains the the fix for this. Still intend to add more features/improvement to the next release. So if everything goes smooth and barring no other bugs, v1.3.3 should be release in the next couple of weeks.

**Comment by zdm** [comment]
Hey, did you forget to release it? ))

**Comment by dadepo** [comment]
Haha. Live happened. 😅 I'll get around to it by this weekend! Thanks for the ping!

**Comment by dadepo** [comment]
version `1.3.3` is now published
