### ISSUE TITLE
Quick check for whether string is an IP, IPv4 or IPv6

### ISSUE THREAD

**Issue by CMCDragonkai** [ip-num/ip-num#78]
I know that the net node module can do this, but since this is the grand ip library for JavaScript, then perhaps these utility functions can be put here to avoid relying on Node functionality.

**Comment by CMCDragonkai** [comment]
There's already function called `isIPv4` but it isn't easy to use since you cannot just pass a string into it.

**Comment by dadepo** [comment]
Hi @CMCDragonkai 
You might want to check the `Validator.isValidIPv4String` and `Validator.isValidIPv6String` functions from the `Validator` module. 

Let me know if these functions meet your need!

**Comment by CMCDragonkai** [comment]
Those are great thanks.
