### ISSUE TITLE
isValidIPv4String() incorrectly returns true for some invalid addresses

### ISSUE THREAD

**Issue by mindjuice** [ip-num/ip-num#9]
Passing values like `1. 2.3.4` (note the extra space after the `1.`) or strings that have additional junk after them like `1.2.3.4xyz` are validated as `true`, but should return `false`.

**Comment by dadepo** [comment]
Thanks for bringing this to my attention. I have fixed it in afee9cb. 
Keeping this ticket open until I push a new release.

**Comment by dadepo** [comment]
v1.1.0 has been published. Thanks!
