### ISSUE TITLE
Subnets don't overlap themselves

### ISSUE THREAD

**Issue by dwarburt** [ip-num/ip-num#93]
Example:
```
import { IPv4CidrRange } from 'ip-num/IPRange';

const net1 = IPv4CidrRange.fromCidr('192.168.0.0/16');
const net2 = IPv4CidrRange.fromCidr('192.168.0.0/16');
console.log(net1.isOverlapping(net2)); // -> false
```

I'm using the `isOverlapping` method as a validator and this behavior surprised me.

**Comment by dadepo** [comment]
Thanks for the PR. I have some other issues I need to work on before a release. I'll try and do this in the next coming week.
